name = "yamp"


[task.build]
command = "go build ."
description = "Build the project"
environment = [
    "CGO_ENABLED=0"
]
depends = [
    "format"
]

[task.format]
command = "go fmt ./..."
description = "Format the project"


[task.run]
command = "go run ."
description = "Run the project"
